### ISSUE TITLE
Update of the cdo package

### ISSUE THREAD

**Issue by portegamon** [cedadev/jasmin_scivm#1]
Hello,

I am working with really large files, and have found that the installed version of the cdo package (1.5.6.1) have problems dealing with them. There is one particular issue (related to chained operators), that has been corrected in the most recent versions (1.5.8 and onwards).

Is it possible to make an update of the version installed?

Many thanks in advance

Pablo

**Comment by alaniwi** [comment]
Pablo,

Sorry for the delay in responding.  I have built this and installed it on jasmin-sci1-test.ceda.ac.uk, which you can use straight away if you want immediate access.  It should soon automatically appear in the yum repository, available for installation on external machines that use JAP.  Installation on the CEDA production nodes will be at a later date, which will be advised to the jasmin-users list.

Regards,
Alan

[keeping ticket open until included in meta RPM]

**Comment by alaniwi** [comment]
Sorry, forgot to mention the version number: 1.6.9

**Comment by portegamon** [comment]
Hi Alan,

Thanks a lot for making the update and letting me know.

regards,
Pablo
