### ISSUE TITLE
update pandas

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#101]
per helpscout 11134

**Comment by alaniwi** [comment]
Clean build but import error: pytz needed.

**Comment by alaniwi** [comment]
Clean import after adding pytz.

**Comment by lukeconibear** [comment]
Was this update installed yesterday?

**Comment by alaniwi** [comment]
Yes. (I need to close a bunch of tickets to reflect that, but I'll do that later because I want to add some labels.)

```
[iwi@jasmin-sci1 ~]$ python2.7
Python 2.7.3 (default, Feb 21 2014, 13:11:38) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
u'0.19.1'
```

**Comment by alaniwi** [comment]
`rpm -qi python27-pandas` gives more info including installation date.

**Comment by lukeconibear** [comment]
Thanks. Sci1 and Sci2 both have version 0.19.1, though Sci3 remains with 0.12.0.

**Comment by alaniwi** [comment]
Okay, sorry about that, I'll raise this with colleagues. Please be aware that in principle these tickets relate to the packaging rather than the installation, so may be closed at any time once the packaging is done. So if necessary any installation issues might have to be raised via the CEDA helpdesk. But on this occasion I am not expecting any significant delay in getting it installed once I point out that the 2TB nodes have been missed.

**Comment by alaniwi** [comment]
Closing ticket that was resolved some time ago.
