### ISSUE TITLE
Update CIS to 1.5.1

### ISSUE THREAD

**Issue by duncanwp** [cedadev/jasmin_scivm#104]
The latest major release now fully supports CIS as a Python library

**Comment by alaniwi** [comment]
@duncanwp Looking into this after long delay - sorry. Where is the latest CIS release please? On pypi I can only see 1.2.0.

**Comment by alaniwi** [comment]
Okay, sorry, found it, https://github.com/cedadev/cis/releases

**Comment by alaniwi** [comment]
Clean build and import for 1.5.4. Various tests ran during the build, so I did not test further.
