### ISSUE TITLE
add scikit-image

### ISSUE THREAD

**Issue by hart-ncg** [cedadev/jasmin_scivm#107]
Could scikit-image be installed please.
It adds much high-level image processing capabality, fundamental to some of my analysis code.
http://scikit-image.org/
https://github.com/scikit-image/scikit-image
Many thanks, Neil

**Comment by alaniwi** [comment]
Sorry for the delay in adding this.

Clean build and import.

Example at http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html#sphx-glr-auto-examples-edges-plot-contours-py (though I see slightly different colours from in the image shown there).

Ready for next release (hopefully Monday 17th July).
