### ISSUE TITLE
Please add gedit to JAP

### ISSUE THREAD

**Issue by samhallam** [cedadev/jasmin_scivm#113]
If not too hard.

**Comment by alaniwi** [comment]
Sorry, but gedit seems to be designed to run inside a GNOME desktop session, and to run properly (without font warnings etc) it requires other GNOME software, which then leaves processes running on the server - not really appropriate for the principal servers that JAP is intended to be run on. There is already a similar notepad-like editor available called "leafpad", which we have included in the JAP. Therefore, sorry, closing as WONTFIX (even though the installation is not difficult as such). I think leafpad should do what you need.
