### ISSUE TITLE
Docker support in the JAP

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/jasmin_scivm#13]
Hi Folks
If we can support Docker in the JAP, and particularly, docker support on the deployed JAP instances on Lotus, users will be able to easily further customize their s/w environment with a relatively low performance penalty. Just how low we wont know until we test it ... so, can we please add docker container support to the standard build that is deployed on Lotus.
(I have easily added it on my Centos 6.5 with an RPM e.g.  https://docs.docker.com/installation/centos/)

**Comment by alaniwi** [comment]
Confirming that the RPM at https://get.docker.com/rpm/1.7.1/centos-6/RPMS/x86_64/docker-engine-1.7.1-1.el6.x86_64.rpm installs on jasmin-sci1-dev. Now to work out what it does...

**Comment by alaniwi** [comment]
I have a vague notion what it does from this ticket and the overview bits of the docs, but whatever it does, it will not run as non-root (get an error about "dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?).  As root, it fails to check out hello-world, when I run `docker run hello-world`, even with proxy-related env vars set (claims to be pulling a repository, but just hangs).

In any case, it appears that it needs to start a daemon to support it (and the RPM ships with the daemon enabled at boot), and there may be concerns about adding packages to the JAP that start daemons.

Action on hold pending face-to-face discussion about this at suitable opportunity, even though adding a pre-built RPM would be fairly trivial.

**Comment by alaniwi** [comment]
Removing "on hold", but need to speak to @mkjpryor-stfc some time, as discussed on Slack. Not planned for 1.1-32 release.

**Comment by agstephens** [comment]
Closing. This is 2 years old.
