### ISSUE TITLE
update python

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#130]
Need to update to a later 2.7.x. Creating ticket but putting on hold because everything will need recompiling, so not for 1.1.32.

Issues to deal with:
* separate out the devel files into separate devel package (and update the build-requires in the python packages)
* get the site-packages under /usr/lib64 instead of /usr/lib, and deal with any hard-coded /usr/lib64 paths in python package builds

**Comment by alaniwi** [comment]
Also check if new build addresses issue in #4

**Comment by alaniwi** [comment]
Comments copied from #146 

From @agstephens:

There are reasons to update python2.7 to python2.7.9 or above. See:

https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support

https://www.python.org/downloads/release/python-279

From @alaniwi:

This would probably require a dedicated "rebuild everything" release of the JAP, with no additional features.

Straightforward enough if everything builds cleanly, but potentially a fair bit of work if it doesn't. Putting on hold until we have a clearer idea of where we are heading with conda, and whether it will replace the JAP.

**Comment by alaniwi** [comment]
(#146 now closed as dup)

**Comment by agstephens** [comment]
Old. So closing.
