### ISSUE TITLE
HDF error using netCD4 in python2.7 

### ISSUE THREAD

**Issue by cdr30** [cedadev/jasmin_scivm#135]
I am getting the following error on jasmin-sci when I try and modify a CMOR compliant netCDF file within python.

```
from netCDF4 import Dataset
# Open file for read/write then close 
ncf = Dataset(cmor_compliant_netcdf_file, 'r+')
... 
ncf.close()  
RuntimeError: NetCDF: HDF error
```

I have checked it is not a file permission issue. Is it possible there is some problem with the netcdf/hdf/libraries installed? 

Cheers,
Chris Roberts

**Comment by agstephens** [comment]
Closing as old (and assumed fixed).
