### ISSUE TITLE
NCO on jasmin-cylc

### ISSUE THREAD

**Issue by abharper** [cedadev/jasmin_scivm#136]
It would be great to have Netcdf operators (NCO) available on cylc. Thanks.

**Comment by alaniwi** [comment]
The JASMIN Analysis Platform already includes NCO. As such, your query appears to be an installation issue on a particular host which does not have the JAP installed. I will contact colleagues to see if this can be installed.

**Comment by agstephens** [comment]
Closed as NCO is available on JASMIN. Dealt with elsewhere.
