### ISSUE TITLE
update CDO

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#138]
Some issues with CDO build - see email correspondence.

~CMOR API has changed, so make sure users are aware.~ [moved to #162]

**Comment by alaniwi** [comment]
CDO 1.9.2 built.

**Comment by alaniwi** [comment]
Following further tests (see helpdesk ticket 17832), there is uncertainty whether 1.9.3 or a 1.9.4 release candidate would be more appropriate. Both build cleanly, but a user has reported run-time issues. Have emailed maintainers to ask.

**Comment by alaniwi** [comment]
Moving CMOR to a separate ticket.

**Comment by agstephens** [comment]
Closed as CDO updated since.
