### ISSUE TITLE
Upgrade Scitools python libraries (iris to 1.8.1, cartopy to 0.11, biggus to 0.8)

### ISSUE THREAD

**Issue by matthew-mizielinski** [cedadev/jasmin_scivm#14]
A new version of iris (1.8.1) has just been released which has a number of features that would make data processing and conversion on lotus more convenient (in particular the lazy loading of data persists when writing that data to disk preventing a simple data conversion script from loading a all data into memory).

Could we please have the current version (1.7.3) updated to 1.8.1?

Matthew

**Comment by alaniwi** [comment]
Latest now iris 1.8.1, cartopy 0.13.0, biggus 0.11.0

**Comment by alaniwi** [comment]
biggus 0.11.0 clean build

**Comment by alaniwi** [comment]
cartopy 0.13.0 requires proj >= 4.8.0

proj is from Fedora project RPM; current version detected as 4.7.1 (RPM claims 4.7.0)

**Comment by alaniwi** [comment]
Later Fedora proj RPM (ftp://fr2.rpmfind.net/linux/fedora/linux/releases/22/Everything/x86_64/os/Packages/p/proj-4.8.0-7.fc22.x86_64.rpm) built against later glibc. Will try rebuilding from source. (ftp://ftp.pbone.net/mirror/download.fedora.redhat.com/pub/fedora/linux/development/22/source/SRPMS/p/proj-4.8.0-7.fc22.src.rpm)

**Comment by alaniwi** [comment]
Fedora proj 4.8.0 SRPM rebuilds cleanly. With this installed, cartopy still not building cleanly:

```
gcc -pthread -fno-strict-aliasing -O2 -g -D_GNU_SOURCE -fPIC -DNDEBUG -O2 -g -D_GNU_SOURCE -fPIC -fPIC -I/usr/include -I./lib/cartopy -I/usr/include -I/usr/include/python2.7 -c lib/cartopy/trace.c -o build/temp.linux-x86_64-2.7/lib/cartopy/trace.o
gcc: lib/cartopy/trace.c: No such file or directory
```

Investigating.

**Comment by alaniwi** [comment]
Latest version of cartopy that gives clean build is 0.11.2 (c.f requested version 0.11.0, that also builds cleanly). 0.12.0 and 0.13.0 both give trace.c missing. Using 0.11.2.

**Comment by alaniwi** [comment]
cartopy build problem reported at https://github.com/SciTools/cartopy/issues/646

**Comment by alaniwi** [comment]
Iris clean build, and imports into python2.7
