### ISSUE TITLE
provide miniconda as RPM

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#143]
From 
https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh

Try to set it up so that the "conda" and "source activate" scripts are available for users without them having to do any further setup (normally have to add bin directory to path), and so that a "conda create" will default to creating an environment somewhere under the user home directory.

Also need to think about interaction / conflict with anaconda RPM if installed.

**Comment by alaniwi** [comment]
Alternatively, try to investigated whatever was giving problems for non-root users of anaconda when I last experimented. Miniconda by contrast seems to "just work" for non-root users.

**Comment by agstephens** [comment]
Closing as "won't fix".
