### ISSUE TITLE
Update version of Python2.7 in JAP - see SSL issue

### ISSUE THREAD

**Issue by agstephens** [cedadev/jasmin_scivm#146]
There are reasons to update python2.7 to python2.7.9 or above. See:

https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support

https://www.python.org/downloads/release/python-279

**Comment by alaniwi** [comment]
This would probably require a dedicated "rebuild everything" release of the JAP, with no additional features.

Straightforward enough if everything builds cleanly, but potentially a fair bit of work if it doesn't.  Putting on hold until we have a clearer idea of where we are heading with conda, and whether it will replace the JAP.

**Comment by alaniwi** [comment]
Duplicate of #130.
