### ISSUE TITLE
Update Community Intercomparison Suite on JAP to version 1.0

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/jasmin_scivm#15]
The Sci machines on JASMIN are running version 0.7.  RSG and AOPP have requested the JAP be updated so that they can get access to version 1.0 of CIS.  CIS version 1.0 is available on PyPI.

**Comment by alaniwi** [comment]
https://pypi.python.org/pypi/jasmin_cis/

**Comment by alaniwi** [comment]
Using version 1.0.0 (rather than 1.0) in tarfile name.  Apparently clean build.  In locally installed RPM on builder, module imports okay.
