### ISSUE TITLE
update iris and ensure iris.tests is included

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#154]
Have been advised that filelock will be needed as a dependency.

If any problem providing latest Iris, still provide filelock.

Per https://ncas-talk.slack.com/archives/C0Q66PALA/p1515768976000140

**Comment by alaniwi** [comment]
Built filelock. Does what it should do with simple test code:

```
import time
from filelock import FileLock

lock = FileLock("/tmp/my.lock")

with lock:
    print "start"
    time.sleep(5)
    print "end"
```
(running more than one instance simultaneously)

**Comment by alaniwi** [comment]
Build `dask` (new dependency).

Not building `pep8` (optional dependency), because this is now replaced by `pycodestyle`, and it appears that Iris will be migrating to it (per https://github.com/SciTools/iris/issues/2941). Built `pycodestyle` but not added as a dependency yet.

**Comment by alaniwi** [comment]
Updated setuptools as required.

**Comment by alaniwi** [comment]
Clean build and import of iris 2.0.0. No special action required to provide `iris.tests` (although on import, a warning about SSL in old python). But trying testing `iris.load` shows that `dask` is missing `toolz` dependency.

**Comment by alaniwi** [comment]
Raised an issue at https://github.com/SciTools/iris/issues/2994 regarding documenting `toolz` as an explicit dependency of `iris` (because it is only an "extras" dependency of dask). Nonetheless, rebuilt dask including most of the optional dependencies (all except `distributed`, which has a bunch of other dependencies including an apparent cyclic dependency on `dask`).

With this done, opening a netCDF file in Iris and extracting some data and metadata seemed to work fine.

**Comment by SHebden** [comment]
Running a python script trying to import iris I get an error message: 'Ambiguous 'iris' package' and details the three options, but I'm not sure how to get it to know I want the scitools one? Thanks for suggestions.

**Comment by peteradeg** [comment]
> Running a python script trying to import iris I get an error message: 'Ambiguous 'iris' package' and details the three options, but I'm not sure how to get it to know I want the scitools one? Thanks for suggestions.

Same problem. Downloaded iris from conda-forge and it is iris 2.1.1 same error message.
 Downgraded to 2.1.0 still same error message when import iris
