### ISSUE TITLE
Please add "ecmwfapi" python library

### ISSUE THREAD

**Issue by agstephens** [cedadev/jasmin_scivm#166]
Hi @alaniwi, please can you add this pip-installable python library to the JAP:

https://software.ecmwf.int/wiki/display/WEBAPI/Accessing+ECMWF+data+servers+in+batch#AccessingECMWFdataserversinbatch-python

Please add it to the next release.

**Comment by alaniwi** [comment]
Adding untested. Builds and imports cleanly. Cannot see example code.

**Comment by alaniwi** [comment]
Or more specifically, cannot see example `.ecmwfapirc` contents. Module imports but `from ecmwfapi import ECMWFDataServer` doesn't without it.

**Comment by alaniwi** [comment]
Okay, missed a bit of the docs. Tested properly now. I appear to have a grib file...
