### ISSUE TITLE
Update required for Iris-grib

### ISSUE THREAD

**Issue by w-k-jones** [cedadev/jasmin_scivm#170]
Please could iris-grib be updated to a newer version, as it is currently not functioning.

The derpeciation of float indexing in numpy causes a "TypeError: 'float' object cannot be interpreted as an index" error when attempting to load a file using v0.9 of iris-grib. This bug was fixed in v0.10.0 and later (see https://github.com/SciTools/iris-grib/pull/75).

Many Thanks, Will

**Comment by alaniwi** [comment]
Clean build and import. Sorry, not further tested. If any further problems are observed once this has been installed on the production systems (installation date will be advised to users hopefully soon) then please raise another issue.
