### ISSUE TITLE
add ILAMB

### ISSUE THREAD

**Issue by caroduro** [cedadev/jasmin_scivm#171]
Would it be possible to get ILAMB (https://bitbucket.org/ncollier/ilamb) installed, for comparing data-model and observations?

**Comment by alaniwi** [comment]
Clean build. Fails at install with `sympy` requirement.

**Comment by alaniwi** [comment]
sympy clean build after fixing a minor manpage issue. sympy import problem - now needs mpmath.

**Comment by alaniwi** [comment]
mpmath built and example at http://mpmath.org/ works.
```
>>> from mpmath import mp
>>> mp.dps = 50
>>> print(mp.quad(lambda x: mp.exp(-x**2), [-mp.inf, mp.inf]) ** 2)
3.1415926535897932384626433832795028841971693993751
```

**Comment by alaniwi** [comment]
Sympy examples now working. (Per https://github.com/sympy/sympy/wiki/Quick-examples .) Rebuilding to add mpmath RPM dependency.

**Comment by alaniwi** [comment]
Needs later cf_units.

**Comment by alaniwi** [comment]
latest cf-units (2.0.2) requires cftime

**Comment by alaniwi** [comment]
cftime clean build and import

**Comment by alaniwi** [comment]
```
ImportError: Bad mpi4py version: ILAMB 2.3 requires mpi4py >= 1.3.1 got 1.3
```

**Comment by alaniwi** [comment]
Updating mpi4py.

Wanted only to update it to 1.3.1, because later releases have different major version, but getting these kind of errors - https://github.com/hashdist/hashstack-old/issues/18 - so will just try the latest version.

**Comment by alaniwi** [comment]
Latest mpi4py not building either. Also tried with mvapich2-devel.

**Comment by alaniwi** [comment]
mpi4py 1.3.1 clean build for both platform_mpi and mpich versions (was using confusing wrong version of spec file lacking fixes for previously solved issues - which will be removed)

**Comment by alaniwi** [comment]
Added dependencies in ILAMB and rebuilt. (Cannot add the dependency for mpi4py directly in ilamb as there are different versions on Sci machine and Lotus, but added these in the relevant places at the top level in the JAP.) Clean import now.
