### ISSUE TITLE
add parallel netCDF properly

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#2]
Have rebuilt netCDF lib with --enable-pnetcdf, but probably doesn't do much without the parallel-netcdf library having been built first. Not publishing revised netcdf RPM or adding to JAP until this is done, because there is no point. Make a version with necessary dependencies for parallel netCDF to work properly, and then add to JAP.

**Comment by alaniwi** [comment]
On hold pending input from NCAS-CMS as per earlier emails.

**Comment by agstephens** [comment]
This is old so closing. It can be re-raised if needed.
