### ISSUE TITLE
update cdo

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#202]
fix the sellonlatbox segfaults by updating to 1.9.7.1. (Now already built the RPM.)

**Comment by duncanwp** [comment]
Is there anyway to load this RPM manually so I can make use of it immediately? Perhaps it could be added as a module?

**Comment by agstephens** [comment]
@duncanwp : please also track this issue which might get a solution sooner: https://github.com/cedadev/ceda-jaspy-envs/issues/1
I am not sure of the timescale for resolving this within the JAP or as an RPM so the conda solution might be quickest.

**Comment by agstephens** [comment]
CDO is now provided via Jaspy:

https://help.jasmin.ac.uk/article/4729-jaspy-envs
