### ISSUE TITLE
upgrade CF checker [was: fix area type table URL in CF checker]

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#21]
From http://cfconventions.org/Data/cf-standard-names/current/src/area-type-table.xml

to http://cfconventions.org/Data/area-type-table/current/src/area-type-table.xml

**Comment by agstephens** [comment]
Hi Alan,
This should be fixed in the source of the cf-checker. See:

 https://github.com/cedadev/cf-checker/commit/8f7d4e16af05222d8eaf3436cd8292c1c5ce0b93

Ag

**Comment by alaniwi** [comment]
Thank you. Leaving ticket open, to fix by upgrading checker in JAP. (Will change title.)

**Comment by alaniwi** [comment]
Built python27-cf-checker-2.0.6-1.ceda.el6.noarch based on commit 8f7d4e1 and tested on builder.

**Comment by alaniwi** [comment]
created basic landing page at https://github.com/cedadev/cf-checker/wiki and pointed the "URL" field in the RPM metadata at it
