### ISSUE TITLE
build GRASS plugin for GDAL

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#28]
https://github.com/cedadev/jasmin_scivm/issues/17 is prerequisite

**Comment by alaniwi** [comment]
for reasons explained at #17 prefer to build plugin. If not possible, built GDAL with GRASS support, but GDAL without GRASS support is a BuildRequires for GRASS, making this approach more complicated to manage.

**Comment by alaniwi** [comment]
gdal-grass 1.11.2 (from http://download.osgeo.org/gdal/gdal-grass-1.11.2.tar.gz) gives build error:
```
g++ -Wall -fPIC  -DUSE_CPL -DGRASS_GISBASE=\"\" -I/usr/include/gdal    -c -o ogrgrassdriver.o ogrgrassdriver.cpp
In file included from ogrgrassdriver.cpp:30:
ogrgrass.h:58: error: conflicting return type specified for ‘virtual int OGRGRASSLayer::GetFeatureCount(int)’

```
return value declared as `int` in `ogrgrasslayer.cpp` and as `GIntBig` (typedef-ed as `long long`) in `/usr/include/gdal/ogr_api.h`, this header file is from `gdal-devel-2.0.0-1.ceda.el6.x86_64`

**Comment by alaniwi** [comment]
`ogr_api.h` unchanged between `gdal-2.0.0` and `gdal-2.0.1` (latest version)

**Comment by alaniwi** [comment]
Similar issue reported with GRASS 7 at http://lists.osgeo.org/pipermail/gdal-dev/2015-July/042286.html - which seems to be unanswered.

**Comment by alaniwi** [comment]
Run out of ideas at present. Putting on hold.

**Comment by danclewley** [comment]
I think this was opened in response to my request to build GRASS (see #17). The GDAL GRASS driver isn't something I need, as easy to export from GRASS using GDAL. I'd be happy if you closed this unless someone else has requested the GRASS driver for GDAL.

**Comment by agstephens** [comment]
Old, so closing.
