### ISSUE TITLE
add nccmp

### ISSUE THREAD

**Issue by kwilliams-mo** [cedadev/jasmin_scivm#34]
Would it be possible to get nccmp (http://nccmp.sourceforge.net/) installed, for comparing netCDF files?

**Comment by alaniwi** [comment]
Built RPM.

Tested, and it seems to work: I took a netCDF file, modified a value by doing ncdump -> text edit -> ncgen, and it found the change (as well as spotting a difference between classic and netCDF4 format for the 2 files).
