### ISSUE TITLE
Issue with build against Python 2.7 lib

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#4]
(Phil K. writes): I am getting a build error when I try to build the Apache module mod_wsgi ( https://github.com/GrahamDumpleton/mod_wsgi/archive/4.4.6.tar.gz) against the Python 2.7 library provided from the JAP RPM.

```
/usr/bin/ld: /usr/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib/libpython2.7.a: could not read symbols: Bad value
```

This appears to be a problem with the library not being compatible with the 64-bit architecture.  I noticed that there is no Python 2.7 library in `/usr/lib64` but that the CentOS Python 2.6 does provide this:

```
# ls -al /usr/lib64 |grep libpython
-r-xr-xr-x.  1 root root  1669840 Feb 22  2013 libpython2.6.so.1.0
[root@localhost mod_wsgi-4.4.6]# ls -al /usr/lib |grep libpython
-rwxr-xr-x   1 root root 3306252 Dec  9  2012 libpython2.7.a
```

~~It would also be helpful to provide the Python 2.7 library as a shared object file as this will reduce the size of executables built against it.~~ (issue moved to https://github.com/cedadev/jasmin_scivm/issues/20)

Can you investigate please?

**Comment by alaniwi** [comment]
@philipkershaw 

Does the machine in question have the latest release I did of python2.7?  In particular, it should say:

```
# rpm -q python27
python27-2.7.3-3.ceda.el6.x86_64
```

An earlier version was not built with PIC.

If I extract the abstract.o (with `ar x /usr/lib/libpython2.7a`) and then do:
```
gcc -shared -o libfoo.so abstract.o
```
it succeeds, but if I do the same with a copy of `abstract.o` extracted from the static library contained in a previous version of the RPM (`python27-2.7.3-1.ceda.el6.x86_64.rpm`), it tells me:

```
$ gcc -shared -o libfoo.so abstract.o
/usr/bin/ld: abstract.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
abstract.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
```
which resembles your error.  So I think this part is probably solved, although it would be good to have confirmation of that.

Regarding other issues:

* use of /usr/lib rather than /usr/lib64 - /usr/lib appears to be the default path when doing a vanilla build of Python from the tarball, even on 64-bit platform.  For the Python 2.6 RPM provided with RHEL6, the use of /usr/lib64 seems to have been brought about by a patch that RedHat put into their RPM.  When building the RPM for Python 2.7, I initially tried to use as many of the RedHat patches written for 2.6 as would apply cleanly, but after significant problems, eventually reverted to doing an RPM based on a vanilla build, although I subsequently added use of PIC back in.  With retrospect, I should probably have also added the patch to move the libs to lib64, but it is too late for that now because it will also affect the location of site packages (currently `/usr/lib/python2.7/site-packages/` rather than `/usr/lib64/...`) and hence all the Python packages would need to be rebuilt - all for not much gain at this stage.

* Providing a shared library - yes, that would be worth looking into, although at this stage I would only do so if in *addition* to a static library, so as not to break things that might use the static library.

Please can you confirm if the above "could not read symbols" error is fixed by ensuring you have the latest version, and if so then I will narrow this ticket down to the provision of a shared object.

**Comment by philipkershaw** [comment]
Hi Alan,  I'll probably need to run through the build error with you so will try and find a time to meet up.

As to a shared library this is a must from my point of view.  It's the default way to link in many cases.  So if you can add it in that would be much appreciated.

**Comment by philipkershaw** [comment]
PS. Sorry just remembered: there is supposed to be a Python 2.7 available from EPEL.  This would almost certainly be a better solution.  However, I'm pretty sure there's no mod_wsgi build for it so including a mod_wsgi.so in the RPM would be helpful.  It would need to have a different naming to avoid clashing with the default one provided with the OS.

**Comment by alaniwi** [comment]
I have not found a Python 2.7 in EPEL. If there is one then please state the URL, although even so it would require rebuilding all the Python packages in JAP, so this would be a task for a later update.

I think I am going to have to separate out this ticket into two separate tickets: one for the shared object file and another for your build error, as otherwise it is hindering progress.

**Comment by alaniwi** [comment]
I have created ticket https://github.com/cedadev/jasmin_scivm/issues/20 regarding the issue of a shared library, and removed that content from this ticket. The scope of this ticket is now the build error. (Phil, please subscribe to that ticket also if required.)

**Comment by alaniwi** [comment]
Labelling as on hold pending Phil showing me the build error in person per above comment.

**Comment by agstephens** [comment]
Closing as we are migrating all to jaspy and python3.7.
