### ISSUE TITLE
create source package for NCL

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#43]
Currently packaging NCL by wrapping binaries distributed by NCAR. Attempt to create a SRPM which does a genuine compilation of the source. Problems with this in the past, so low priority.

**Comment by alaniwi** [comment]
Also request from a user - if this is done - to include ESMF.

Some instructions supplied via a sysadmin at Leeds:

{{{

these are my notes for adding esmf to the ncl 6.2.0 install. it doesn't
look like i explicitly set the compiler anywhere, i think it picks this
up from:

build_config/Linux.gfortran.default/build_rules.mk

within the esmf source directory.

i don't believe this has to be installed within the ncl directories,
that was just where it seemed to make sense to put the software on our
systems - the esmf executables can be anywhere in your PATH.

#--

# change '/path/to/ncl/install/dir' and 'netcdf library flags' as required.

#-

# esmf:
# download from: http://www.earthsystemmodeling.org/download/releases.shtml

# make install dir:

mkdir /path/to/ncl/install/dir/esmf

# extract:

tar xzf ../src/esmf_6_3_0rp1_src.tar.gz
cd esmf

# variables:

ESMF_DIR="`pwd`"
ESMF_COMM="mpiuni"
ESMF_ABI="64"
ESMF_OS="Linux"
ESMF_INSTALL_PREFIX="/path/to/ncl/install/dir/esmf"
export ESMF_DIR ESMF_COMM ESMF_ABI ESMF_OS ESMF_INSTALL_PREFIX
ESMF_NETCDF="user"
ESMF_NETCDF_INCLUDE="${NETCDF}/include"
ESMF_NETCDF_LIBPATH="${NETCDF}/lib"
ESMF_NETCDF_LIBS="netcdf library flags"
export ESMF_NETCDF ESMF_NETCDF_INCLUDE ESMF_NETCDF_LIBPATH ESMF_NETCDF_LIBS
CFLAGS="-fPIC -O2 "
CXXFLAGS="-fPIC -O2 "
FFLAGS="-fPIC -O2 "
FCFLAGS="-fPIC -O2 "
export CFLAGS CXXFLAGS FFLAGS FCFLAGS

# build!:

make -j8 &&
make check &&
make install

#- stupid install dirs:

cp
/path/to/ncl/install/dir/esmf/bin/binO/Linux.gfortran.64.mpiuni.default/*
/path/to/ncl/install/dir/esmf/bin/

cp
/path/to/ncl/install/dir/esmf/lib/libO/Linux.gfortran.64.mpiuni.default/*
/path/to/ncl/install/dir/esmf/lib/

cp
/path/to/ncl/install/dir/esmf/mod/modO/Linux.gfortran.64.mpiuni.default/*
/path/to/ncl/install/dir/esmf/mod/

#-

# to run, these variables are set:

prepend PATH esmf/bin
prepend LIBRARY_PATH esmf/lib
prepend LD_LIBRARY_PATH esmf/lib

#--
}}}

**Comment by alaniwi** [comment]
Considerations added re ESMF in #40 apply here too: do not include ESMF executables, but add a dependency instead.

**Comment by agstephens** [comment]
NCL is now available on Jaspy.
