### ISSUE TITLE
GDAL Python scripts use system Python rather than 2.7

### ISSUE THREAD

**Issue by danclewley** [cedadev/jasmin_scivm#57]
For example running gdal_merge.py on the JASMIN SCIVM (tested on cems-sci2.cems.rl.ac.uk) gives the following error: 
```
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 37, in <module>
    import gdal
ImportError: No module named gdal
```
The cause of this error is all the GDAL Python scripts have
```
#!/usr/bin/env python
```
so run using the system Python (2.6) rather than the Python GDAL was build for.

I think this could be fixed by adding the following line to the spec:
```
sed -i 's|/usr/bin/env python|/usr/bin/env python2.7|g' swig/python/scripts/*py
```

**Comment by alaniwi** [comment]
Python scripts all over the place. Trying with global search/replace
```
find . -name '*.py' -type f | xargs sed -i 's,^#!/usr/bin/env python$,#!/usr/bin/env python2.7,'
```

**Comment by alaniwi** [comment]
Seems to have fixed it. Ready for installation as part of next JAP release (hopefully next week).
