### ISSUE TITLE
request to upgrade to R (3.3.0) and to install  the  Snowfall R library on Lotus 

### ISSUE THREAD

**Issue by dch1fc** [cedadev/jasmin_scivm#75]
Dear all, 
the current version of R installed on LOTUS is  R version 3.2.1 (2015-06-18) I would need to use the most recent version which is R (3.3.0).
and I need the Snowfall library (the R library used for
parallel computing on clusters).

Many Thanks,
Fatima

**Comment by alaniwi** [comment]
R can be updated to 3.3.1. Will mark this ticket as RPM ready as there is one from RedHat, and I will bump the version in the meta RPM.

WONTFIX regarding Snowfall. This has been discussed separately. It is not compatible with the version of MPI that we use.
