### ISSUE TITLE
GNU Parallel

### ISSUE THREAD

**Issue by rrniii** [cedadev/jasmin_scivm#78]
It would be good to add GNU Parallel to the jasmin_scivm in order for users to utilise multiple processors  on machines that do not have access to super computers like LOTUS.

At Leeds we utilise this application to do a "poor man's" parallelisation of our code across our 64 core machine.

**Comment by alaniwi** [comment]
RPM built.

Also added a patch to remove conspicuous messages about citation that can otherwise only be silenced by typing "will cite", because it might not be appropriate for users to cite every link in a large toolchain. `--help` text still includes the citation.
