### ISSUE TITLE
Update GDAL version to 2.1 for Sentinel 2 Driver

### ISSUE THREAD

**Issue by danclewley** [cedadev/jasmin_scivm#81]
Update GDAL to version 2.1 for next build as as this includes a driver for Sentinel 2
(http://www.gdal.org/frmt_sentinel2.html).
Currently on version 2.0 so should only be a minor change.

**Comment by alaniwi** [comment]
Existing RPM is based on Fedora source RPM for 2.0 with various local changes (mainly to ensure that the python bindings are for 2.7). Grafting source tarball for 2.1.1 into this does not work (various patches don't apply) - unsurprisingly also as it is a complicated spec file. This will require looking for a Fedora source RPM for 2.1.x and then applying similar changes to what were done for 2.0.

**Comment by alaniwi** [comment]
Details of previous upgrade at https://github.com/cedadev/jasmin_scivm/issues/6

**Comment by alaniwi** [comment]
Latest rawhide RPM for gdal is 2.0.2.

**Comment by alaniwi** [comment]
Found Fedora RPM at ftp://fr2.rpmfind.net/linux/fedora/linux/development/rawhide/Everything/source/tree/Packages/g/gdal-2.1.1-1.fc26.src.rpm

**Comment by alaniwi** [comment]
Applied various changes to spec file along the lines of those done for 2.0.0, and now building. From experience, build takes hours, so to check on later, but expecting that some trial and error will be needed.
