### ISSUE TITLE
Please install psycopg2 library and dependencies

### ISSUE THREAD

**Issue by agstephens** [cedadev/jasmin_scivm#97]
Please install the psycopg2 (http://pythonhosted.org/psycopg2/) package for python2.7.

I have managed to install it on top of the existing JAP with:

```
$ yum install -y postgresql
$ yum install -y postgresql-devel
$ pip install psycopg2

**Comment by alaniwi** [comment]
Clean RPM build and import. Added postgresql as RPM dependency (although not as direct dependency of meta RPM). postgresql-devel added as build-time dependency only.

**Comment by alaniwi** [comment]
https://github.com/cedadev/jasmin_scivm/commit/3b54914224de80c838fb08986de4afcb4db8457f

**Comment by alaniwi** [comment]
Provided in 1.1-31. Long overdue close.
